server:
  port: 9527


spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
          # 路由的id，没有固定规则但是要求唯一
        - id: provider-01
          # 匹配后提供服务的路由地址
          uri: lb://provider-01
          # 断言，路径匹配的进行路由
          predicates:
#            根据路径匹配
            - Path=/provider01/**
##            根据请求时间匹配
#            - After=2020-09-12T13:10:07.398+08:00[Asia/Shanghai]
##            请求中必须符合cookie正则，可以多个
#            - Cookie=username, tom
#            - Cookie=age, 18
##             请求中头信息必须符合正则
#            - Header=userId, 992
          filters:
#            添加请求头
            - AddRequestHeader= hshsd, ${server.port}

            - StripPrefix=1

#        - id: provider-01-01
#          uri: lb://provider-01
#          predicates:
#            - Path=/provider01/**

        - id: provider-02
          uri: lb://provider-02
          predicates:
            - Path=/test02/**

eureka:
  client:
    #    是否要自己注册到EUREKA 上
    register-with-eureka: true
    #    不需要去服务注册中心获取其他服务地址
    fetch-registry: true
    service-url:
      defaultZone:  http://EUREKA01:7001/eureka/


